#!/bin/bash
clear
opcion=1

while [ $opcion -ne 0 ] ;
do
clear
tput cup 3 3; echo "[1] Libros"

tput cup 5 3; echo "[2] Videos"

tput cup 7 3; echo "[0] Volver"

tput cup 9 3; read -p "Ingrese Opcion deseada: " opcion

case $opcion in

1)clear
tput cup 3 30; echo "Ingrese Usuario: "
tput cup 3 46; read usu
tput cup 5 30; echo "Ingrese cedula: "
tput cup 5 46; read cedu

grep  "$usu" administracion.txt>variables2
log2=$(cat -n variables2 | cut -d: -f2,7)
echo $usu:$cedu>>prueba.txt
log=$(grep "$usu" prueba.txt)
log3=$(echo $log2)
log4=$(echo $log)

if    [ $log3 = $log4 ]
then

clear

rm variables2
rm prueba.txt

tput cup 3 3; read -p "Ingrese ISBN:" isbn

grep -w "$isbn" prestamosl.txt>>biblioteca.txt
grep -w "$isbn" prestamosl.txt>>libros.txt

grep -v "$isbn" prestamosl.txt>>biblioteca3.txt
rm prestamosl.txt
mv biblioteca3.txt prestamosl.txt

grep -v "$isbn" consultorio.txt>>biblioteca3.txt
rm consultorio.txt
mv biblioteca3.txt consultorio.txt

grep -v "$isbn" vencidos.txt>>biblioteca3.txt
rm vencidos.txt
mv biblioteca3.txt vencidos.txt

else
echo "Nombre de usuario o cedula incorrectos"
sleep 3
rm prueba.txt
rm variables2
fi

;;

2)

tput cup 3 30; echo "Ingrese Usuario: "
tput cup 3 46; read usu
tput cup 5 30; echo "Ingrese cedula: "
tput cup 5 46; read cedu

grep  "$usu" administracion.txt>variables2
log2=$(cat -n variables2 | cut -d: -f2,7)
echo $usu:$cedu>>prueba.txt
log=$(grep "$usu" prueba.txt)
log3=$(echo $log2)
log4=$(echo $log)

if    [ $log3 = $log4 ]
then

clear

rm variables2
rm prueba.txt

tput cup 3 3; read -p "Ingrese ISSN:" issn
grep "$issn" prestamosv.txt>>biblioteca.txt
grep "$issn" prestamosv.txt>>videos.txt

grep -v "$issn" prestamosv.txt>>biblioteca3.txt
rm prestamosv.txt
mv biblioteca3.txt prestamosv.txt

grep -v "$issn" consultorio2.txt>>biblioteca3.txt
rm consultorio2.txt
mv biblioteca3.txt consultorio2.txt

grep -v "$isbn" vencidos.txt>>biblioteca3.txt
rm vencidos.txt
mv biblioteca3.txt vencidos.txt

else
echo "Nombre de usuario o cedula incorrectos"
sleep 3
rm prueba.txt
rm variables2
fi

;;

0) clear ;;

*) echo "Opcion ingresada no valida, intentelo de nuevo" ;;

esac
done
